# Generated by Django 3.2.2 on 2021-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210513_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(
                choices=[
                    ('Breakfast', 'Завтрак'),
                    ('Lunch', 'Обед'),
                    ('Supper', 'Ужин')],
                max_length=50),
        ),
    ]
