# Generated by Django 3.2.2 on 2021-05-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210529_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='author',
            new_name='user',
        ),
    ]
