# Generated by Django 3.2.2 on 2021-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210605_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                blank=True,
                through='recipes.RecipeIngredient',
                to='recipes.Ingredient',
                verbose_name='Ингредиенты'),
        ),
    ]
