# Generated by Django 3.2.2 on 2021-07-03 09:30

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210703_1138'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='unique_favorite'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='unique_purchase'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('author',
                     django.db.models.expressions.F('user')),
                    _negated=True),
                name='user_and_author_not_equal'),
        ),
    ]
